Make the UUID mandatory
pubnub/java pull request #228
Opened 2021-12-17 15:17 UTC by kleewho

2021-12-17 15:38 UTC, bartk requested changes

2021-12-17 15:38 UTC, bartk commented on src/main/java/com/pubnub/api/PubNubUtil.java
> +    public static void requirePN(boolean value, PubNubError error) throws PubNubException {
maybe just `require()`?

2021-12-17 15:38 UTC, bartk commented on src/test/java/com/pubnub/contract/MockPubnubService.kt
> +class A {
Do we need that class?

2022-01-05 09:35 UTC, kleewho commented on src/main/java/com/pubnub/api/PubNubUtil.java
> +    public static void requirePN(boolean value, PubNubError error) throws PubNubException {
done

2022-01-05 09:35 UTC, kleewho commented on src/test/java/com/pubnub/contract/MockPubnubService.kt
> +class A {
Nope :)

2022-01-05 10:03 UTC, bartk submitted a review, later dismissed

2022-01-11 12:22 UTC, bartk submitted a review, later dismissed

2022-01-12 14:25 UTC, kleewho commented
@client-engineering-bot release as v6.0.0

2022-01-12 14:35 UTC, kazydek approved these changes

2022-01-12 14:54 UTC, bartk approved these changes

2022-01-12 15:16 UTC, merged